### ISSUE TITLE
Modify "Going Remote" Page

### ISSUE THREAD

**Issue by skarya22** [mcgill-ecsess/codejam2020#37]
I noticed that under the heading: "Are company representatives going to be present at CodeJam 2020?," the text list looks darker than the rest of the text on the page.

**Comment by kellydanma** [comment]
It was intentional as part of the current theme because the default colour for bullet points is different. I can just remove the bullet points and write a full sentence to rectify the colour mismatch.

**Comment by kellydanma** [comment]
Updated with [a73cf31](https://github.com/mcgill-ecsess/codejam2020/pull/42/commits/a73cf31f929bd9ff0900f00fed7f6e940719ae03)
