### ISSUE TITLE
Modify the FAQ pages

### ISSUE THREAD

**Issue by skarya22** [mcgill-ecsess/codejam2020#38]
All of the FAQ pages have a "Your question wasn’t listed?" section, should we add a link to the Contact page so that people can see the up to date information such as phone number? 
And, should the sponsoring page really be a part of FAQs?

**Comment by kellydanma** [comment]
The sponsoring page should be visible in as many places as possible so as to encourage companies to click on it. With the current design (we didn't create the theme itself, only modified the content), it is a subheading of FAQ.

We will be removing the phone number so as to avoid spam. A lot of spam-callers scrape websites for viable phone numbers; the reason we added a `mailto:` is to facilitate sponsor interaction. It's easier than redirecting them to multiple pages.

Feel free to open another issue to migrate it to its own page! It's not high priority in the backlog atm so it might take a while to get to it. We're aiming to complete the website ASAP.

**Comment by kellydanma** [comment]
I'm closing this because migrating the sponsorship page merits its own issue and PR.
