### ISSUE TITLE
Consistant CodeJam vs Code.Jam()

### ISSUE THREAD

**Issue by skarya22** [mcgill-ecsess/codejam2020#39]
On the home page, CodeJam is referred to as "CodeJam" everywhere, but on the about page it is soleely referred to as "Code.Jam()", should we make it Code.Jam() everywhere on the home page too?

**Comment by kellydanma** [comment]
Yes!

**Comment by kellydanma** [comment]
Consolidated with [34b8827](https://github.com/mcgill-ecsess/codejam2020/pull/42/commits/34b8827c8de851521cafa2f893c8eafd1365141d)
