### ISSUE TITLE
Potential Change in FAQs General Page

### ISSUE THREAD

**Issue by skarya22** [mcgill-ecsess/codejam2020#40]
Under "Who is eligible to participate?" I thought that during a meeting, we decided no high school students? Correct me if I am wrong tho

**Comment by kellydanma** [comment]
I haven't attended all of the meetings, this data was simply pooled from previous years' websites. I'll remove the high-school eligibility.

**Comment by kellydanma** [comment]
Removed with [04f47f6](https://github.com/mcgill-ecsess/codejam2020/pull/42/commits/04f47f68a955323fa68443b37e3e70a012f81e71)
