### ISSUE TITLE
Small Changes in FAQs Resources Page

### ISSUE THREAD

**Issue by skarya22** [mcgill-ecsess/codejam2020#41]
- Under "Recommended software" → "Visual Studio Code" change "favorite" to "favourite" 😜

- Fix spelling of "libraries" in "Useful librairies and frameworks" (there is an extra 'i')

**Comment by kellydanma** [comment]
_Canadianized_ the word `favourite` with [dbc0ad3](https://github.com/mcgill-ecsess/codejam2020/pull/42/commits/dbc0ad3571f9d3f2158a5afcccaa321442a20ec9)

**Comment by kellydanma** [comment]
Correct spelling with [0af0308](https://github.com/mcgill-ecsess/codejam2020/pull/42/commits/0af03087f02e800d3211b4878dc7220f59353968)
